export var CartasMissaoCombateQueimadas = {
    1: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo0.png', tipo: 'ATK'},
    2: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo1.png', tipo: 'ATK'},
    3: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo2.png', tipo: 'ATK'},
    4: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo3.png', tipo: 'ATK'},
    5: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo4.png', tipo: 'ATK'},
    6: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo5.png', tipo: 'ATK'},
    7: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo6.png', tipo: 'ATK'},
    8: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo7.png', tipo: 'ATK'},
    9: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo8.png', tipo: 'ATK'},
    10: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaFogo9.png', tipo: 'ATK'},
    11: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaJogador1.png', tipo: 'EST'},
    12: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaJogador9.png', tipo: 'EST'},
    13: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaJogador3.png', tipo: 'EST'},
    14: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/CartaJogadorX.png', tipo: 'EST'},
    15: { caminhoImagem: '/Baralho_Capital/Front_end/TelaJogo/MissaoCombateQueimadas/imagensMissaoQueimadas/cartas/RoupaAntiChamas.png', tipo: 'DEF'},
}
